spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://linguaroots.onrender.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/auth/**,/superadmin/**,/admin/**,/student/**

        - id: lesson-service
          uri: lb://LESSON-MANAGEMENT
          predicates:
            - Path=/lesson/**

        - id: post-service
          uri: lb://POST-MANAGEMENT
          predicates:
            - Path=/post/**,/comment/**

      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.loadbalancer: DEBUG

debug: true