spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/auth/**,/superadmin/**,/admin/**,/student/**

        - id: lesson-service
          uri: lb://LESSON-MANAGEMENT
          predicates:
            - Path=/lesson/**,/word/**

        - id: post-service
          uri: lb://POST-MANAGEMENT
          predicates:
            - Path=/post/**,/comment/**,/reply/**,/like/**

      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

file:
  upload-dir: ${UPLOAD_DIR:uploads}