spring.application.name=Post-Management
server.port = 8092

#database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/Lingua_PM
spring.datasource.url=jdbc:postgresql://postgres:5432/Lingua_PM
spring.datasource.username=postgres
spring.datasource.password=claudia@2603
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka

# Example for supporting up to 100MB audio/video files
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# Files larger than this will be written to a temp disk location instead of RAM
spring.servlet.multipart.file-size-threshold=2MB