spring.application.name=service-registry
server.port=8761

#host name for the server
eureka.instance.hostname=localhost
#so that the server does not fetch the registry
eureka.client.fetch-registry=false
#so that the server does not register himself
eureka.client.register-with-eureka=false

spring.security.user.name=admin
spring.security.user.password=admin123